name: cysm
description: les go

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.5+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  get: ^4.3.8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  enum_to_string: ^2.0.1
  marquee: ^2.2.0
  flutter_compass: ^0.7.0
  geolocator: ^9.0.0
  loading_indicator: ^3.0.2
  vector_math: ^2.1.0
  mocktail: ^0.3.0
  fake_cloud_firestore: ^1.1.3
  flutter_launcher_icons: ^0.9.2
  rounded_loading_button: ^2.1.0
  async_button_builder: ^2.2.0+1
  flutter_timer_countdown: ^1.0.3
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  cloud_functions: ^3.3.1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/android_logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/niira_compass_basic.png
    - assets/arrow_niira_sm.png
    - assets/arrow_niira_sm.png
    - assets/crystal_.png
    - assets/swiper.jpeg

